/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.airticketbooking;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
//import java.util.logging.Level;
//import java.util.logging.Logger;

/**
 *
 * @author Rakesh
 */
public class cancellation extends javax.swing.JFrame {

    /**
     * Creates new form cancellation
     */
    static cancellation c;
    AirTicketBookingUI a;
    int st=1;
    
    public cancellation() {
        initComponents();
    }
    
    public void createRef(AirTicketBookingUI a){
        this.a=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter PNR id to cancel your ticket");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(243, 243, 243))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTextField1.getAccessibleContext().setAccessibleName("input_pnr");
        jTextField1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        status s = new status();
        s.createRef1(a);
        s.setVisible(true);
        String pnr = jTextField1.getText();
        int flag=0;
        String path1="C:/Users/satwik/Desktop/flightsgui/";
        if(pnr.length()!=11)
        {
            st=0;
            //System.out.println("PNR ID does not exist");
            //System.exit(0);
        }
        String fromcity=pnr.substring(0,1);
        String tocity=pnr.substring(1,2);
        String date1=pnr.substring(2,7);
        String flightname=pnr.substring(7,8);
        date1=date1+"-2018";
        String seatno=pnr.substring(8,11);
        int result;
        result = -1;
        try{
            result = Integer.parseInt(seatno.substring(1,3));
        }
        catch(NumberFormatException e){
            st=0;
            //jTextField1.setText("PNR ID doesnot exist");
            //System.exit(0);
        }
        switch(fromcity)
        {
            case "B":fromcity="Bangalore";break;
            case "C":fromcity="Chennai";break;
            case "M":fromcity="Mumbai";break;
            case "D":fromcity="Delhi";break;
            case "K":fromcity="Kolkata";break;
            case "T":fromcity="Trivendrum";break;
            case "H":fromcity="Hyderabad";break;
            case "N":fromcity="Nagpur";break;
        }
        switch(tocity)
        {
            case "B":tocity="Bangalore";break;
            case "C":tocity="Chennai";break;
            case "M":tocity="Mumbai";break;
            case "D":tocity="Delhi";break;
            case "K":tocity="Kolkata";break;
            case "T":tocity="Trivendrum";break;
            case "H":tocity="Hyderabad";break;
            case "N":tocity="Nagpur";break;
        }
        switch(flightname)
        {
            case "S":flightname="Spicejet";break;
            case "A":flightname="AirIndia";break;
            case "I":flightname="Indigo";break;
            case "J":flightname="Jetairways";break;
        }
        path1=path1+fromcity+"-"+tocity+"/"+date1+"/"+flightname+".txt";
        String newContent1="",oldContent1="";
        try
        {
            File f=new File(path1);
            if(f.isFile()==false){
                st=0;
                //jTextField1.setText("PNR Id doesnot exist");
                //System.exit(0);
            }                                     /*removing the booked ticket---start*/
            String line1;
            FileWriter writer;
            try (BufferedReader reader = new BufferedReader(new FileReader(f))) {
                line1 = "";
                for(int i=0;i<13;i++)
                {
                    line1=reader.readLine();
                    oldContent1=oldContent1 + line1 + System.lineSeparator();
                }       while(line1!=null)
                {
                    line1=reader.readLine();
                    if(line1==null)
                        break;
                    if(line1.length()<11)
                        continue;
                    String sub=line1.substring(0,11);
                    if(pnr.equals(sub)!=true)
                    {
                        oldContent1=oldContent1 + line1 + System.lineSeparator();
                    }
                    else
                        flag=1;
        }       writer = new FileWriter(f);
                newContent1=oldContent1;
                writer.write(newContent1);
            }
            System.out.println(flag);
            System.out.println(path1);
        writer.close();                   /*end*/
        if(flag==1)
        {                                             
            File f1=new File(path1);                                     /*replacing the ticket number back----start*/
            FileWriter writer1;                                          
                try (BufferedReader reader1 = new BufferedReader(new FileReader(f1))) {
                    oldContent1="";
                    //newContent1;
                    for(int i=0;i<5;i++)
                    {
                        line1=reader1.readLine();
                        oldContent1=oldContent1 + line1 + System.lineSeparator();
                    }       if(seatno.substring(0,1).equals("R"))
                    {
                        line1=reader1.readLine();
                        if(result>=1 && result<=10)
                        {
                            String line2=line1.substring(0,8)+line1.substring(8,8+5*(result-1))+seatno+line1.substring(8+5*(result-1)+3);
                            oldContent1=oldContent1 + line2 + System.lineSeparator();
                        }
                        
                        if(result>=11 && result<=20)
                        {
                            oldContent1=oldContent1 + line1 + System.lineSeparator();
                            line1=reader1.readLine();
                            result=result-10;
                            String line2=line1.substring(0,8)+line1.substring(8,8+5*(result-1))+seatno+line1.substring(8+5*(result-1)+3);
                            oldContent1=oldContent1 + line2 + System.lineSeparator();
                        }
                    }       if(seatno.substring(0,1).equals("L"))
                    {
                        for(int i=0;i<3;i++)
                        {
                            line1=reader1.readLine();
                            oldContent1=oldContent1 + line1 + System.lineSeparator();
                        }
                        line1=reader1.readLine();
                        if(result>=1 && result<=10)
                        {
                            String line2=line1.substring(0,8)+line1.substring(8,8+5*(result-1))+seatno+line1.substring(8+5*(result-1)+3);
                            oldContent1=oldContent1 + line2 + System.lineSeparator();
                        }
                        
                        if(result>=11 && result<=20)
                        {
                            oldContent1=oldContent1 + line1 + System.lineSeparator();
                            line1=reader1.readLine();
                            result=result-10;
                            String line2=line1.substring(0,8)+line1.substring(8,8+5*(result-1))+seatno+line1.substring(8+5*(result-1)+3);
                            oldContent1=oldContent1 + line2 + System.lineSeparator();
                        }
                    }       line1=reader1.readLine();
                    while(line1!=null)
                    {
                        oldContent1=oldContent1 + line1 + System.lineSeparator();
                        line1=reader1.readLine();
                    }
                    writer1 = new FileWriter(f1);
                    newContent1=oldContent1;
                    writer1.write(newContent1);
                    reader1.close();
                    writer1.close();
                }
            //System.out.print("Your ticket has been cancelled\n\n");
            //System.out.print("Your money will be credited to your account shortly\n\n"); 
        }                                              /*end*/
        else{
            st=0;
            //System.out.println("PNR id does not exist");} 
        }
        }
        catch(NullPointerException e)
        {
            st=0;
            //System.out.println(e);
        } catch (IOException ex) {
            st=0;
            //Logger.getLogger(cancellation.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.createRef2(st);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
