/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.airticketbooking;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Rakesh
 */
public class pass extends javax.swing.JFrame {

    AirTicketBookingUI a = new AirTicketBookingUI();
    static pass p = new pass();
    printPass pp = new printPass();
    int st=1,flag=0;
    status s = new status();
    
    /**
     * Creates new form pass
     * @param a
     */
    
    public void createRef(AirTicketBookingUI a){
        this.a=a;
    }
    
    public pass() {
        initComponents();
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter PNR id");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pnr1,path1="C:/Users/satwik/Desktop/flightsgui/";
   //System.out.printf("enter your PNR number : ");
   pnr1=jTextField1.getText();
   a.pnr1=pnr1;
   if(pnr1.length()!=11)
   {
       st=0;
     //System.out.println("PNR ID does not exist");
     //System.exit(0);
   }
   String fromcity=pnr1.substring(0,1);
   String tocity=pnr1.substring(1,2);
   String date1=pnr1.substring(2,7);
   String flightname=pnr1.substring(7,8);
   date1=date1+"-2018";
   a.date=date1;
   String seatno=pnr1.substring(8,11);
   int result=-1;
   try{
	result = Integer.parseInt(seatno.substring(1,3));
   }
   catch(NumberFormatException e){
        st=0;
	//System.out.println("PNR ID doesnot exist");
        //System.exit(0);
   }
   switch(fromcity)
   {
    case "B":fromcity="Bangalore";break;
    case "C":fromcity="Chennai";break;
    case "M":fromcity="Mumbai";break;
    case "D":fromcity="Delhi";break;
    case "K":fromcity="Kolkata";break;
    case "T":fromcity="Trivendrum";break;
    case "H":fromcity="Hyderabad";break;
    case "N":fromcity="Nagpur";break;
   }
   a.from=fromcity;
   switch(tocity)
   {
    case "B":tocity="Bangalore";break;
    case "C":tocity="Chennai";break;
    case "M":tocity="Mumbai";break;
    case "D":tocity="Delhi";break;
    case "K":tocity="Kolkata";break;
    case "T":tocity="Trivendrum";break;
    case "H":tocity="Hyderabad";break;
    case "N":tocity="Nagpur";break;
   }
   a.to=tocity;
   switch(flightname)
   {
    case "S":flightname="Spicejet";break;
    case "A":flightname="AirIndia";break;
    case "I":flightname="Indigo";break;
    case "J":flightname="Jetairways";break;
   }
   a.flightname=flightname;
    path1=path1+fromcity+"-"+tocity+"/"+date1+"/"+flightname+".txt";
   String name="",oldContent1="";
   try
   {
    File f=new File(path1);
    if(f.isFile()==false){
        st=0;
	//System.out.println("PNR Id doesnot exist");
	//System.exit(0);
    }                                         /*removing the booked ticket---start*/
    BufferedReader reader = new BufferedReader(new FileReader(f));
    String line1="";
    a.flightno = reader.readLine();
    a.departure = reader.readLine();
 
    a.arrival = reader.readLine();

    a.duration = reader.readLine();
     
    a.price = reader.readLine();
    String lin1="";
    for(int i=0;i<8;i++)
    {
     line1=reader.readLine();
    }
    while(line1!=null)
    {
       line1=reader.readLine();
       if(line1==null)
          break;
       if(line1.length()<11)
          continue;
       String sub=line1.substring(0,11);
       if(pnr1.equals(sub)==true)
       {
        a.name=line1.substring(12);
        flag=1;
        break;
       }
    } 
  }
  catch(IOException e)
   {
       st=0;
   // System.out.println(e);
   }
   dispose();
    if(flag==1)
    {
        //dispose();
        pp.setVisible(true);
        pp.createRef(a);
    }
    else{
        //dispose();
        s.setVisible(true);
        s.createRef2(st);
        //s.createRef1(a);
    }
        //s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
