/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.airticketbooking;

import java.awt.Font;

/**
 *
 * @author Rakesh
 */
public class printPass extends javax.swing.JFrame {

    /**
     * Creates new form printPass
     */
    //static cancellation c;
    AirTicketBookingUI a;
    
    public void createRef(AirTicketBookingUI a){
        this.a=a;
        jTextArea1.setFont(new Font("monospaced", Font.BOLD, 14));
        jTextArea1.setText("  ___________________________________________________________________________________\n");
        jTextArea1.append("                                                                                     \n");
        jTextArea1.append("                             B O A R D I N G      P A S S                                \n");
        jTextArea1.append("                                                                                     \n");
        jTextArea1.append("  ___________________________________________________________________________________\n");
        jTextArea1.append("                                                                                     \n");
        jTextArea1.append("                                   "+a.flightname.toUpperCase());
        jTextArea1.append("                                                                                     \n");
        jTextArea1.append("  ___________________________________________________________________________________\n");
        jTextArea1.append("                                                                                     \n");
	jTextArea1.append("                                                                                     \n");
	jTextArea1.append("                                      "+a.date+"               \n");
	jTextArea1.append("                        "+String.format("%-9s",a.from.toUpperCase())+"    ----------->      "+a.to.toUpperCase()+"                       \n");
	jTextArea1.append("                        "+a.departure+"      "+a.duration+"        "+a.arrival+"                       \n");
	jTextArea1.append("                                                                                     \n");
	jTextArea1.append("                                                                                     \n");
	jTextArea1.append("     Pnr                         Passenger name                 Seat no.             \n");
	jTextArea1.append("    ---------------------------------------------------------------------            \n");		
        jTextArea1.append("     "+a.pnr1+"                 "+String.format("%-31s",a.name)+"\n");
	jTextArea1.append("                                                                                     \n");
	jTextArea1.append("  Baggage info :   Check-in: 25 KG, Cabin: 8 KG                                        \n");
	jTextArea1.append("                                                                                     \n");
	jTextArea1.append("  TIP: The air inside airplane is dry, so drink nonalcoholic beverages               \n");
	jTextArea1.append("       Note the PNR Id(s) for future reference                                       \n");
	jTextArea1.append("                                                                                     \n");
	jTextArea1.append("  Terms and Conditions :                                                             \n");
	jTextArea1.append("   1.Check-in counters at all Airports opens 2 hours before departure                \n");
	jTextArea1.append("   2.Your carry-on baggage shouldn't weigh more than 8kgs                            \n");
	jTextArea1.append("   3.Carry photo identiy, you will need it as proof of identity while checking-in	 \n");
	jTextArea1.append("   4.Cancellation charges apply according to date and time of cancellation           \n");
	jTextArea1.append("   5.Cancellation amount will be refunded to your bank account with in 3-5 days      \n");
	jTextArea1.append("  ___________________________________________________________________________________\n");
	jTextArea1.append("		                                                                         \n");
	jTextArea1.append("		            H A P P Y                 J O U R N E Y                      \n");
	jTextArea1.append("  ___________________________________________________________________________________");
        jTextArea1.setEditable(false);
    }
    
    public printPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BOARDING PASS");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
