/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.airticketbooking;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.*;


/**
 *
 * @author satwik
 */
public class seatSelect extends javax.swing.JFrame {
    AirTicketBookingUI a;
    static seatSelect ss;
    javax.swing.JCheckBox[] cb;
    String oldContent = "",newContent="",temp="";
    BufferedReader reader;
    File f;
    
    /**
     * Creates new form seatSelect
     */
    public seatSelect() {
        initComponents();
        cb = new javax.swing.JCheckBox[40];
        cb[0]=jCheckBox1;
        cb[1]=jCheckBox2;
        cb[2]=jCheckBox3;
        cb[3]=jCheckBox4;
        cb[4]=jCheckBox5;
        cb[5]=jCheckBox6;
        cb[6]=jCheckBox7;
        cb[7]=jCheckBox8;
        cb[8]=jCheckBox9;
        cb[9]=jCheckBox10;
        cb[10]=jCheckBox11;
        cb[11]=jCheckBox12;
        cb[12]=jCheckBox13;
        cb[13]=jCheckBox14;
        cb[14]=jCheckBox15;
        cb[15]=jCheckBox16;
        cb[16]=jCheckBox17;
        cb[17]=jCheckBox18;
        cb[18]=jCheckBox19;
        cb[19]=jCheckBox20;
        cb[20]=jCheckBox21;
        cb[21]=jCheckBox22;
        cb[22]=jCheckBox23;
        cb[23]=jCheckBox24;
        cb[24]=jCheckBox25;
        cb[25]=jCheckBox26;
        cb[26]=jCheckBox27;
        cb[27]=jCheckBox28;
        cb[28]=jCheckBox29;
        cb[29]=jCheckBox30;
        cb[30]=jCheckBox31;
        cb[31]=jCheckBox32;
        cb[32]=jCheckBox33;
        cb[33]=jCheckBox34;
        cb[34]=jCheckBox35;
        cb[35]=jCheckBox36;
        cb[36]=jCheckBox37;
        cb[37]=jCheckBox38;
        cb[38]=jCheckBox39;
        cb[39]=jCheckBox40;
    }
    
    public void createRef(AirTicketBookingUI a)
    {
        this.a=a;
        setSeats();
    }
    
    public void setSeats()
    {
        try
        {
            f = new File(a.path);
            
            reader = new BufferedReader(new FileReader(f));
            a.flightno = reader.readLine();
             oldContent = oldContent + a.flightno + System.lineSeparator();
            a.departure = reader.readLine();
             oldContent = oldContent + a.departure + System.lineSeparator();
            a.arrival = reader.readLine();
            oldContent = oldContent + a.arrival + System.lineSeparator();
            a.duration = reader.readLine();
            oldContent = oldContent + a.duration + System.lineSeparator();
            a.price = reader.readLine();
            oldContent = oldContent + a.price + System.lineSeparator();
            String line = reader.readLine();
            temp = temp + line + System.lineSeparator();
            int j=0;
            for(int i=8;i<=53;i=i+5)
            {
                if(line.charAt(i)!='R')
                    cb[j].setEnabled(false);
                j++;
            }
            line = reader.readLine();
            temp = temp + line + System.lineSeparator();
            for(int i=8;i<=53;i=i+5)
            {
                if(line.charAt(i)!='R')
                    cb[j].setEnabled(false);
                j++;
            }
            line = reader.readLine();
            temp = temp + line + System.lineSeparator();
            line = reader.readLine();
            temp = temp + line + System.lineSeparator();
            for(int i=8;i<=53;i=i+5)
            {
                if(line.charAt(i)!='L')
                    cb[j].setEnabled(false);
                j++;
            }
            line = reader.readLine();
            temp = temp + line + System.lineSeparator();
            for(int i=8;i<=53;i=i+5)
            {
                if(line.charAt(i)!='L')
                    cb[j].setEnabled(false);
                j++;
            }
            
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox42 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Select Seats:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("P");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("I");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("L");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("O");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("T");

        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox1.setHideActionText(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox11)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox12)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox13)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox14)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox15)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox16)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox17)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox18)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox19)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox4)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox5)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox6)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox7)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox9)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jCheckBox31)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox32)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox33)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox34)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox35)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox36)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox37)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox38)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox39)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox40))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jCheckBox21)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox22)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox23)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox24)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox25)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox26)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox27)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox28)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox29)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox30))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jCheckBox22)
                            .addComponent(jCheckBox23)
                            .addComponent(jCheckBox24)
                            .addComponent(jCheckBox25)
                            .addComponent(jCheckBox26)
                            .addComponent(jCheckBox27)
                            .addComponent(jCheckBox28)
                            .addComponent(jCheckBox29)
                            .addComponent(jCheckBox30))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jCheckBox40)
                            .addComponent(jCheckBox39)
                            .addComponent(jCheckBox38)
                            .addComponent(jCheckBox37)
                            .addComponent(jCheckBox36)
                            .addComponent(jCheckBox35)
                            .addComponent(jCheckBox34)
                            .addComponent(jCheckBox33)
                            .addComponent(jCheckBox32)
                            .addComponent(jCheckBox31)))
                    .addComponent(jCheckBox21))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jCheckBox1.getAccessibleContext().setAccessibleName("R01");
        jCheckBox2.getAccessibleContext().setAccessibleName("R02");
        jCheckBox3.getAccessibleContext().setAccessibleName("R03");
        jCheckBox4.getAccessibleContext().setAccessibleName("R04");
        jCheckBox5.getAccessibleContext().setAccessibleName("R05");
        jCheckBox6.getAccessibleContext().setAccessibleName("R06");
        jCheckBox7.getAccessibleContext().setAccessibleName("R07");
        jCheckBox8.getAccessibleContext().setAccessibleName("R08");
        jCheckBox9.getAccessibleContext().setAccessibleName("R09");
        jCheckBox10.getAccessibleContext().setAccessibleName("R10");
        jCheckBox11.getAccessibleContext().setAccessibleName("R11");
        jCheckBox12.getAccessibleContext().setAccessibleName("R12");
        jCheckBox13.getAccessibleContext().setAccessibleName("R13");
        jCheckBox14.getAccessibleContext().setAccessibleName("R14");
        jCheckBox15.getAccessibleContext().setAccessibleName("R15");
        jCheckBox16.getAccessibleContext().setAccessibleName("R16");
        jCheckBox17.getAccessibleContext().setAccessibleName("R17");
        jCheckBox18.getAccessibleContext().setAccessibleName("R18");
        jCheckBox19.getAccessibleContext().setAccessibleName("R19");
        jCheckBox20.getAccessibleContext().setAccessibleName("R20");
        jCheckBox22.getAccessibleContext().setAccessibleName("L02");
        jCheckBox23.getAccessibleContext().setAccessibleName("L03");
        jCheckBox24.getAccessibleContext().setAccessibleName("L04");
        jCheckBox25.getAccessibleContext().setAccessibleName("L05");
        jCheckBox26.getAccessibleContext().setAccessibleName("L06");
        jCheckBox27.getAccessibleContext().setAccessibleName("L07");
        jCheckBox28.getAccessibleContext().setAccessibleName("L08");
        jCheckBox29.getAccessibleContext().setAccessibleName("L09");
        jCheckBox30.getAccessibleContext().setAccessibleName("L10");
        jCheckBox31.getAccessibleContext().setAccessibleName("L11");
        jCheckBox32.getAccessibleContext().setAccessibleName("L12");
        jCheckBox33.getAccessibleContext().setAccessibleName("L13");
        jCheckBox34.getAccessibleContext().setAccessibleName("L14");
        jCheckBox35.getAccessibleContext().setAccessibleName("L15");
        jCheckBox36.getAccessibleContext().setAccessibleName("L16");
        jCheckBox37.getAccessibleContext().setAccessibleName("L17");
        jCheckBox38.getAccessibleContext().setAccessibleName("L18");
        jCheckBox39.getAccessibleContext().setAccessibleName("L19");
        jCheckBox40.getAccessibleContext().setAccessibleName("L20");
        jCheckBox21.getAccessibleContext().setAccessibleName("L01");

        jCheckBox41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox41.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("- Not Available");

        jCheckBox42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox42.setText(" -   Available");

        jButton1.setText("Next >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox41)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox42)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String seat;
        
        
        for(int i=0;i<cb.length;i++)
        {
            if(cb[i].isSelected()==true)
                a.al.add(cb[i].getAccessibleContext().getAccessibleName());
            
        }
        System.out.println(a.al);
        a.pnr = new String[a.al.size()];
        for(int i=0;i<a.al.size();i++)
        {
            seat=a.al.get(i).toString();
            a.pnr[i]=a.from.substring(0,1)+a.to.substring(0,1)+a.date.substring(0,5)+a.flightname.substring(0,1)+seat;
            //oldContent = oldContent.replaceAll(seat,"NA ");
            temp = temp.replaceAll(seat,"NA ");
        }
        try
        {
            oldContent+=temp;
            String line=reader.readLine();
            while(line!=null)
            {
                oldContent = oldContent + line + System.lineSeparator();
                line=reader.readLine();
            }
        FileWriter writer = new FileWriter(f);
        System.out.println(oldContent);
        writer.write(oldContent);
        reader.close();
        writer.close();
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }
        dispose();
        NewJFrame p = new NewJFrame();
        p.createRef(a,f);
        p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seatSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seatSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seatSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seatSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ss=new seatSelect();
                ss.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
